### PR TITLE
add frontend files

### PR DESCRIPTION
**Pull request by armedillaalliyah**
Please review my code, Thank you!

### CODE REVIEW

**Review by fidel-dianarose — COMMENTED** [review]
Your script.js violates the coding guidelines. In line 11-26 , there is a function inside a function. Refer to the coding guidelines below. 

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g2651733a4ec_0_9

**Comment by armedillaalliyah** [comment]
Please review my code @dnrsfdl

**Comment by dnrsfdl** [comment]
Replace your timer.html file with index.html and update your readme.md.

**Review by fidel-dianarose — COMMENTED** [review]
Replace your timer.html file with index.html and update your readme.md.

**Comment by armedillaalliyah** [comment]
Please review my code @dnrsfdl, Thank you!

**Review by alima-kailamarie — APPROVED** [review]
I already see the changes in your readme file. You can merge it to the main branch.

**Pull request merged**
